@echo off
REM Terminal launcher. The trading bots are STOPPED by decision, not by
REM fault - see the block at section 5.
REM   Every MT5_PATH_<n> / MT5_OPEN_<n> terminal opens for manual use.
REM
REM The us_fleet* YAMLs are still generated by scripts\gen_us_fleet.py and
REM are not in the repo. They now serve as the symbol LIST for the alerts
REM and for buy_and_hold.py; nothing reads their strategy settings.

cd /d "%~dp0"

REM UTF-8: a shortcut path can contain Japanese, and python-dotenv reads
REM .env as UTF-8, so cmd must read it the same way or the path arrives as
REM mojibake and reads as "not found on disk".
chcp 65001 >nul

REM ==== 1. Read MT5 terminal paths from .env ====
if not exist ".env" (
    echo [start.bat] .env not found
    pause
    exit /b 1
)
REM Suffixes 1-9 cover every account; unset ones are skipped, so a new
REM account needs only its MT5_PATH_<n> line in .env - nothing to edit here.
for %%n in (1 2 3 4 5 6 7 8 9) do set "MT5_PATH_%%n="
for %%n in (1 2 3 4 5 6 7 8 9) do set "MT5_OPEN_%%n="
REM delims is "=" AND space, so KEY = value and indented lines parse too.
for /f "usebackq tokens=1,* delims== " %%a in (".env") do (
    for %%n in (1 2 3 4 5 6 7 8 9) do (
        if /I "%%a"=="MT5_PATH_%%n" set "MT5_PATH_%%n=%%~b"
        if /I "%%a"=="MT5_OPEN_%%n" set "MT5_OPEN_%%n=%%~b"
        if /I "%%a"=="MT5_SHORTCUT_%%n" set "MT5_OPEN_%%n=%%~b"
    )
)
echo [start.bat] terminal entries read from .env:
for %%n in (1 2 3 4 5 6 7 8 9) do call :show_entry "MT5_PATH_%%n"
for %%n in (1 2 3 4 5 6 7 8 9) do call :show_entry "MT5_OPEN_%%n"

REM The three bot accounts must be present; the rest are optional.
for %%n in (1 2 4) do (
    call :require_path %%n || exit /b 1
)

REM ==== 2. Launch one terminal per configured account ====
REM Every path is started AT MOST ONCE, and one shared by two entries opens a
REM single time - a /portable terminal does not dedupe itself, so starting it
REM repeatedly just piles up windows.
REM   MT5_PATH_<n>   account <n>'s terminal. Opened here, and ALSO the
REM                  account the bots and the reports connect to under that
REM                  suffix - naming a terminal here puts it in the reports.
REM   MT5_OPEN_<n>   just open this, nothing else: no account, no bot, no
REM                  report. Takes an exe or a .lnk; a shortcut keeps its
REM                  target's arguments, which is what /portable needs.
REM                  (MT5_SHORTCUT_<n> still works as an older spelling.)
REM Nothing is scanned: only what .env names is opened.
set "LAUNCHED_PATHS="
for %%n in (1 2 3 4 5 6 7 8 9) do call :launch_one "MT5_PATH_%%n" "account-%%n terminal"
for %%n in (1 2 3 4 5 6 7 8 9) do call :launch_one "MT5_OPEN_%%n" "extra terminal %%n"

echo [start.bat] waiting 30 seconds for the terminals to load and auto-login...
timeout /t 30 /nobreak >nul

REM ==== 3. Verify venv ====
if not exist ".venv\Scripts\activate.bat" (
    echo [start.bat] .venv not found.
    echo Run: python -m venv .venv ^&^& .venv\Scripts\activate ^&^& pip install -r requirements.txt
    pause
    exit /b 1
)

REM ==== 4. Verify the generated fleet dirs exist ====
call :require_fleet "config\us_fleet" || exit /b 1

REM ==== 5. Bots: STOPPED ====
REM Four strategies passed an out-of-sample backtest and lost live, while
REM simply holding the same 100 symbols returned about +21% over the same
REM window - a roughly 45-point gap against doing nothing. Measuring the
REM two phenomena that might have justified a different approach found
REM cross-sectional reversal indistinguishable from zero before costs.
REM
REM So the fleets no longer launch. The book is now built by
REM scripts\buy_and_hold.py, which is a portfolio state rather than a
REM loop: there is no exit rule, so there is nothing to poll for.
REM
REM Before restoring any line below, the bar is no longer 'positive in a
REM backtest'. It is 'beats holding the same symbols, out of sample, after
REM costs' - which none of the four ever cleared.
REM
REM start "clau-stock account 1 (macd)" cmd /k "call .venv\Scripts\activate.bat && python -u scripts\run_live.py --account 1 config\us_fleet\*.yaml"
REM start "clau-stock account 2 (macd+stoch)" cmd /k "call .venv\Scripts\activate.bat && python -u scripts\run_live.py --account 2 config\us_fleet_a2\*.yaml"
REM start "clau-stock account 4 (bollrci)" cmd /k "call .venv\Scripts\activate.bat && python -u scripts\run_live.py --account 4 config\us_fleet_a4\*.yaml"

REM Price-change alerts still run: they place no orders, and a move worth
REM looking at is still worth being told about.
start "clau-stock alerts" cmd /k "call .venv\Scripts\activate.bat && python -u scripts\run_alerts.py --account 1 config\watchlist.yaml config\us_fleet\*.yaml"

echo.
echo [start.bat] trading bots are STOPPED by decision - see section 5
echo [start.bat] the book is built by: scripts\buy_and_hold.py --account 1 config\us_fleet\*.yaml
echo [start.bat] launched alerts (watchlist.yaml extras + the account-1 fleet)
echo Logs: logs\alerts1.log
echo.
pause
exit /b 0

:show_entry
call set "p=%%%~1%%"
if defined p echo [start.bat]   %~1 = %p%
exit /b 0

:launch_one
REM %1 = name of the variable holding the path, %2 = label for the log
call set "p=%%%~1%%"
if not defined p exit /b 0
REM Explorer hides the .lnk extension, so accept the name with or without it
if not exist "%p%" if exist "%p%.lnk" set "p=%p%.lnk"
if not exist "%p%" (
    echo [start.bat] WARNING: %~1 not found on disk: %p%
    exit /b 0
)
echo "%LAUNCHED_PATHS%"| findstr /i /c:"[%p%]" >nul
if not errorlevel 1 (
    echo [start.bat] %~2 already opened: %p%
    exit /b 0
)
set "LAUNCHED_PATHS=%LAUNCHED_PATHS%[%p%]"
echo [start.bat] launching %~2: %p%
start "" "%p%"
exit /b 0

:require_path
setlocal
call set "p=%%MT5_PATH_%1%%"
if not defined p (
    echo [start.bat] MT5_PATH_%1 not set in .env
    pause
    endlocal
    exit /b 1
)
if not exist "%p%" (
    echo [start.bat] MT5_PATH_%1 not found on disk: %p%
    pause
    endlocal
    exit /b 1
)
endlocal
exit /b 0

:require_fleet
if not exist "%~1\*.yaml" (
    echo [start.bat] %~1 has no YAMLs - generate the fleet first with
    echo     scripts\gen_us_fleet.py  (see README "US fleet" section^)
    pause
    exit /b 1
)
exit /b 0
