@echo off
REM Terminal launcher, and the bots for accounts 2 and 4 - see section 5.
REM   Account 1  no bot. Buy and hold, built by scripts\buy_and_hold.py.
REM   Account 2  macd + H4 + stoch   (config\us_fleet_a2)
REM   Account 4  bollrci             (config\us_fleet_a4)
REM   Every MT5_PATH_<n> / MT5_OPEN_<n> terminal opens for manual use.
REM
REM The us_fleet* YAMLs are generated by scripts\gen_us_fleet.py and are not
REM in the repo. us_fleet_a2 and us_fleet_a4 carry the settings their bots
REM run; us_fleet is now only a symbol LIST, for the alerts and for
REM buy_and_hold.py - nothing reads its strategy settings.

cd /d "%~dp0"

REM UTF-8: a shortcut path can contain Japanese, and python-dotenv reads
REM .env as UTF-8, so cmd must read it the same way or the path arrives as
REM mojibake and reads as "not found on disk".
chcp 65001 >nul

REM ==== 1. Read MT5 terminal paths from .env ====
if not exist ".env" (
    echo [start.bat] .env not found
    pause
    exit /b 1
)
REM Suffixes 1-9 cover every account; unset ones are skipped, so a new
REM account needs only its MT5_PATH_<n> line in .env - nothing to edit here.
for %%n in (1 2 3 4 5 6 7 8 9) do set "MT5_PATH_%%n="
for %%n in (1 2 3 4 5 6 7 8 9) do set "MT5_OPEN_%%n="
REM delims is "=" AND space, so KEY = value and indented lines parse too.
for /f "usebackq tokens=1,* delims== " %%a in (".env") do (
    for %%n in (1 2 3 4 5 6 7 8 9) do (
        if /I "%%a"=="MT5_PATH_%%n" set "MT5_PATH_%%n=%%~b"
        if /I "%%a"=="MT5_OPEN_%%n" set "MT5_OPEN_%%n=%%~b"
        if /I "%%a"=="MT5_SHORTCUT_%%n" set "MT5_OPEN_%%n=%%~b"
    )
)
echo [start.bat] terminal entries read from .env:
for %%n in (1 2 3 4 5 6 7 8 9) do call :show_entry "MT5_PATH_%%n"
for %%n in (1 2 3 4 5 6 7 8 9) do call :show_entry "MT5_OPEN_%%n"

REM The three bot accounts must be present; the rest are optional.
for %%n in (1 2 4) do (
    call :require_path %%n || exit /b 1
)

REM ==== 2. Launch one terminal per configured account ====
REM Every path is started AT MOST ONCE, and one shared by two entries opens a
REM single time - a /portable terminal does not dedupe itself, so starting it
REM repeatedly just piles up windows.
REM   MT5_PATH_<n>   account <n>'s terminal. Opened here, and ALSO the
REM                  account the bots and the reports connect to under that
REM                  suffix - naming a terminal here puts it in the reports.
REM   MT5_OPEN_<n>   just open this, nothing else: no account, no bot, no
REM                  report. Takes an exe or a .lnk; a shortcut keeps its
REM                  target's arguments, which is what /portable needs.
REM                  (MT5_SHORTCUT_<n> still works as an older spelling.)
REM Nothing is scanned: only what .env names is opened.
set "LAUNCHED_PATHS="
for %%n in (1 2 3 4 5 6 7 8 9) do call :launch_one "MT5_PATH_%%n" "account-%%n terminal"
for %%n in (1 2 3 4 5 6 7 8 9) do call :launch_one "MT5_OPEN_%%n" "extra terminal %%n"

echo [start.bat] waiting 30 seconds for the terminals to load and auto-login...
timeout /t 30 /nobreak >nul

REM ==== 3. Verify venv ====
if not exist ".venv\Scripts\activate.bat" (
    echo [start.bat] .venv not found.
    echo Run: python -m venv .venv ^&^& .venv\Scripts\activate ^&^& pip install -r requirements.txt
    pause
    exit /b 1
)

REM ==== 4. Verify the generated fleet dirs exist ====
REM One per launching bot, plus us_fleet for the alerts and buy_and_hold.
REM A missing dir is not a warning: run_live would start, match no YAML and
REM sit there doing nothing, which reads exactly like a working bot.
call :require_fleet "config\us_fleet" || exit /b 1
call :require_fleet "config\us_fleet_a2" || exit /b 1
call :require_fleet "config\us_fleet_a4" || exit /b 1

REM ==== 5. Bots: accounts 2 and 4 only ====
REM Account 1 does NOT launch a bot. Its book is buy and hold, built by
REM scripts\buy_and_hold.py - a portfolio state rather than a loop, with no
REM exit rule and so nothing to poll for. A bot there would also be bidding
REM for margin the held book is already using.
REM
REM Accounts 2 and 4 keep running, by decision. The case for it: every live
REM figure so far was taken while restarts re-fired stale signals - 32 of
REM 104 entries on account 1 had no backtest signal at all - and that was
REM fixed in fdf71cd. So no strategy has yet had a clean live test, and on
REM a demo account the run costs nothing but attention.
REM
REM The case against, recorded so it is not rediscovered later: "the
REM strategy was fine, the execution was broken, run it again" is how a
REM dead strategy stays alive. The contamination was ~31%; removing it does
REM not obviously turn -24% positive.
REM
REM The bar is unchanged and is NOT 'positive in a backtest', nor 'beats
REM zero'. It is 'beats holding the same symbols over the same window,
REM after costs'. scripts\monthly_report.py now reports the held book
REM beside the traded one, so that comparison is a table rather than an
REM argument.
start "clau-stock account 2 (macd+stoch)" cmd /k "call .venv\Scripts\activate.bat && python -u scripts\run_live.py --account 2 config\us_fleet_a2\*.yaml"
start "clau-stock account 4 (bollrci)" cmd /k "call .venv\Scripts\activate.bat && python -u scripts\run_live.py --account 4 config\us_fleet_a4\*.yaml"

REM start "clau-stock account 1 (macd)" cmd /k "call .venv\Scripts\activate.bat && python -u scripts\run_live.py --account 1 config\us_fleet\*.yaml"

REM Price-change alerts still run: they place no orders, and a move worth
REM looking at is still worth being told about.
start "clau-stock alerts" cmd /k "call .venv\Scripts\activate.bat && python -u scripts\run_alerts.py --account 1 config\watchlist.yaml config\us_fleet\*.yaml"

echo.
echo [start.bat] bots running: account 2 (macd+stoch), account 4 (bollrci)
echo [start.bat] account 1 has NO bot - it is buy and hold:
echo [start.bat]   scripts\buy_and_hold.py --account 1 config\us_fleet\*.yaml
echo [start.bat] launched alerts (watchlist.yaml extras + the account-1 fleet)
echo Logs: logs\live2.log logs\live4.log logs\alerts1.log
echo.
pause
exit /b 0

:show_entry
call set "p=%%%~1%%"
if defined p echo [start.bat]   %~1 = %p%
exit /b 0

:launch_one
REM %1 = name of the variable holding the path, %2 = label for the log
call set "p=%%%~1%%"
if not defined p exit /b 0
REM Explorer hides the .lnk extension, so accept the name with or without it
if not exist "%p%" if exist "%p%.lnk" set "p=%p%.lnk"
if not exist "%p%" (
    echo [start.bat] WARNING: %~1 not found on disk: %p%
    exit /b 0
)
echo "%LAUNCHED_PATHS%"| findstr /i /c:"[%p%]" >nul
if not errorlevel 1 (
    echo [start.bat] %~2 already opened: %p%
    exit /b 0
)
set "LAUNCHED_PATHS=%LAUNCHED_PATHS%[%p%]"
echo [start.bat] launching %~2: %p%
start "" "%p%"
exit /b 0

:require_path
setlocal
call set "p=%%MT5_PATH_%1%%"
if not defined p (
    echo [start.bat] MT5_PATH_%1 not set in .env
    pause
    endlocal
    exit /b 1
)
if not exist "%p%" (
    echo [start.bat] MT5_PATH_%1 not found on disk: %p%
    pause
    endlocal
    exit /b 1
)
endlocal
exit /b 0

:require_fleet
if not exist "%~1\*.yaml" (
    echo [start.bat] %~1 has no YAMLs - generate the fleet first with
    echo     scripts\gen_us_fleet.py  (see README "US fleet" section^)
    pause
    exit /b 1
)
exit /b 0
