"""Generate a per-symbol config fleet for the OOS-validated macd+breadth recipe.

Connects to the account, auto-discovers the broker's US-stock symbols with the
same discover_universe used by the live breadth gate (venue duplicates like
NVIDIA.24h deduped), and writes one YAML per symbol to --out-dir, each with a
distinct magic number. Prints the run_live command when done.

Defaults are fleet-safe rather than single-symbol-safe: per_trade_pct 0.5 (the
repo default 3.0 is fine for one gold bot, but the breadth gate synchronises
entries across the whole universe — a strong regime can open many positions in
the same week) and max_total_positions 8 as the account-wide backstop.

Usage:
    python scripts/gen_us_fleet.py --account 1
    python scripts/gen_us_fleet.py --account 1 --per-trade-pct 1.0 --max-total-positions 10
    python scripts/gen_us_fleet.py --account 1 --with-stoch   # after its OOS passes
"""
from __future__ import annotations

import argparse
import os
import re
import sys
from pathlib import Path

from dotenv import load_dotenv

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "src"))

from gold_trader.breadth import discover_universe  # noqa: E402
from gold_trader.mt5_client import MT5Credentials, connect  # noqa: E402

TEMPLATE = """\
# {symbol}: macd + US-stock breadth regime gate (OOS-validated recipe).
# Generated by scripts/gen_us_fleet.py — regenerate rather than hand-edit
# fleet-wide changes.
symbol: {symbol}
timeframe: H1
strategy: macd

macd:
  fast: 12
  slow: 26
  signal: 9
  use_h4_filter: false
{stoch_block}
breadth:
  use: true
  lookback: {lookback}
  min_net: {min_net}

risk:
  per_trade_pct: {per_trade_pct}
  atr_stop_mult: 2.0
  max_positions: 1
  max_total_positions: {max_total}

execution:
  magic_number: {magic}
  comment: macd_breadth
"""

STOCH_BLOCK = """
stoch:
  use: true
  overbought: 80.0
  oversold: 20.0
"""


def _slug(symbol: str) -> str:
    return re.sub(r"[^a-z0-9]", "_", symbol.lower())


def main() -> None:
    p = argparse.ArgumentParser(description="generate the US macd+breadth fleet")
    p.add_argument("--account", default=None, help="env-var suffix (MT5_LOGIN_N ...)")
    p.add_argument("--out-dir", default="config/us_fleet")
    p.add_argument("--per-trade-pct", type=float, default=0.5)
    p.add_argument("--max-total-positions", type=int, default=8)
    p.add_argument("--min-net", type=float, default=1)
    p.add_argument("--lookback", type=int, default=100)
    p.add_argument("--magic-base", type=int, default=20260700)
    p.add_argument("--with-stoch", action="store_true",
                   help="also enable the stochastic gate (stoch+breadth combo) "
                        "— flip on once its OOS check passes")
    args = p.parse_args()

    load_dotenv()
    suffix = f"_{args.account}" if args.account else ""
    try:
        creds = MT5Credentials(
            login=int(os.environ[f"MT5_LOGIN{suffix}"]),
            password=os.environ[f"MT5_PASSWORD{suffix}"],
            server=os.environ[f"MT5_SERVER{suffix}"],
            path=os.environ.get(f"MT5_PATH{suffix}") or None,
        )
    except KeyError as missing:
        sys.stderr.write(f"missing env var {missing}\n")
        sys.exit(2)

    with connect(creds) as mt5:
        names = [s.name for s in (mt5.symbols_get() or [])]
    universe = discover_universe(names)
    if not universe:
        sys.stderr.write("no US-stock symbols found on this broker\n")
        sys.exit(2)

    out = Path(args.out_dir)
    out.mkdir(parents=True, exist_ok=True)
    paths = []
    for i, symbol in enumerate(sorted(universe)):
        text = TEMPLATE.format(
            symbol=symbol,
            lookback=args.lookback,
            min_net=f"{args.min_net:g}",
            per_trade_pct=f"{args.per_trade_pct:g}",
            max_total=args.max_total_positions,
            magic=args.magic_base + i,
            stoch_block=STOCH_BLOCK if args.with_stoch else "",
        )
        path = out / f"macd_breadth_{_slug(symbol)}.yaml"
        path.write_text(text, encoding="utf-8")
        paths.append(path)
        print(f"wrote {path}  ({symbol})")

    print(f"\n# {len(paths)} configs. Worst case if every entry fires: "
          f"{args.max_total_positions} positions x {args.per_trade_pct:g}% "
          f"= {args.max_total_positions * args.per_trade_pct:g}% of equity at risk.")
    acct = f" --account {args.account}" if args.account else ""
    print(f"# launch:\n#   python scripts/run_live.py{acct} {out}/*.yaml")


if __name__ == "__main__":
    main()
