"""Generate a per-symbol config fleet for the OOS-validated macd+breadth recipe.

Connects to the account, auto-discovers the broker's US-stock symbols with the
same discover_universe used by the live breadth gate (venue duplicates like
NVIDIA.24h deduped), and writes one YAML per symbol to --out-dir, each with a
distinct magic number. Prints the run_live command when done.

Defaults are fleet-safe rather than single-symbol-safe: per_trade_pct 0.5 (the
repo default 3.0 is fine for one gold bot, but the breadth gate synchronises
entries across the whole universe — a strong regime can open many positions in
the same week) and max_total_positions 8 as the account-wide backstop.

Usage:
    python scripts/gen_us_fleet.py --account 1
    python scripts/gen_us_fleet.py --account 1 --per-trade-pct 1.0 --max-total-positions 10
    python scripts/gen_us_fleet.py --account 1 --with-stoch   # after its OOS passes
"""
from __future__ import annotations

import argparse
import os
import re
import sys
from pathlib import Path

from dotenv import load_dotenv

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "src"))

from gold_trader.breadth import discover_from_paths, discover_universe  # noqa: E402
from gold_trader.mt5_client import MT5Credentials, connect  # noqa: E402

TEMPLATE = """\
# {symbol}: macd + US-stock breadth regime gate (OOS-validated recipe).
# Generated by scripts/gen_us_fleet.py — regenerate rather than hand-edit
# fleet-wide changes.
symbol: {symbol}
timeframe: H1
strategy: macd

macd:
  fast: 12
  slow: 26
  signal: 9
  use_h4_filter: false
{stoch_block}
breadth:
  use: true
  lookback: {lookback}
  min_net: {min_net}
  universe_path: "{universe_path}"
  max_universe: {max_universe}

risk:
  per_trade_pct: {per_trade_pct}
  atr_stop_mult: 2.0
  max_positions: 1
  max_total_positions: {max_total}

execution:
  magic_number: {magic}
  comment: macd_breadth
"""

STOCH_BLOCK = """
stoch:
  use: true
  overbought: 80.0
  oversold: 20.0
"""


def _slug(symbol: str) -> str:
    return re.sub(r"[^a-z0-9]", "_", symbol.lower())


def main() -> None:
    p = argparse.ArgumentParser(description="generate the US macd+breadth fleet")
    p.add_argument("--account", default=None, help="env-var suffix (MT5_LOGIN_N ...)")
    p.add_argument("--out-dir", default="config/us_fleet")
    p.add_argument("--per-trade-pct", type=float, default=0.5)
    p.add_argument("--max-total-positions", type=int, default=8)
    p.add_argument("--min-net", type=float, default=1)
    p.add_argument("--lookback", type=int, default=100)
    p.add_argument("--magic-base", type=int, default=20260700)
    p.add_argument("--with-stoch", action="store_true",
                   help="also enable the stochastic gate (stoch+breadth combo) "
                        "— flip on once its OOS check passes")
    p.add_argument("--universe-path", default="",
                   help="discover symbols from the broker's own US-equity group "
                        "(MT5 symbol path fragment, e.g. 'us') instead of the "
                        "curated US_STOCKS list — scales to hundreds of names")
    p.add_argument("--max-universe", type=int, default=200,
                   help="cap on symbols used for the live breadth tally "
                        "(0 = all). Breadth is an aggregate; ~200 estimates the "
                        "same regime as 1000 at a fraction of the fetch cost")
    p.add_argument("--limit", type=int, default=0,
                   help="generate at most this many configs (0 = all discovered)")
    args = p.parse_args()

    load_dotenv()
    suffix = f"_{args.account}" if args.account else ""
    try:
        creds = MT5Credentials(
            login=int(os.environ[f"MT5_LOGIN{suffix}"]),
            password=os.environ[f"MT5_PASSWORD{suffix}"],
            server=os.environ[f"MT5_SERVER{suffix}"],
            path=os.environ.get(f"MT5_PATH{suffix}") or None,
        )
    except KeyError as missing:
        sys.stderr.write(f"missing env var {missing}\n")
        sys.exit(2)

    with connect(creds) as mt5:
        syms = mt5.symbols_get() or []
        if args.universe_path:
            entries = [(s.name, getattr(s, "path", "") or "") for s in syms]
            universe = discover_from_paths(entries, args.universe_path)
        else:
            universe = discover_universe([s.name for s in syms])
    if not universe:
        where = (f"path containing {args.universe_path!r}" if args.universe_path
                 else "the curated US_STOCKS list")
        sys.stderr.write(f"no US-stock symbols found on this broker via {where}\n")
        sys.exit(2)
    if args.limit > 0:
        universe = sorted(universe)[:args.limit]

    out = Path(args.out_dir)
    out.mkdir(parents=True, exist_ok=True)
    paths = []
    for i, symbol in enumerate(sorted(universe)):
        text = TEMPLATE.format(
            symbol=symbol,
            lookback=args.lookback,
            min_net=f"{args.min_net:g}",
            per_trade_pct=f"{args.per_trade_pct:g}",
            max_total=args.max_total_positions,
            magic=args.magic_base + i,
            stoch_block=STOCH_BLOCK if args.with_stoch else "",
            universe_path=args.universe_path,
            max_universe=args.max_universe,
        )
        path = out / f"macd_breadth_{_slug(symbol)}.yaml"
        path.write_text(text, encoding="utf-8")
        paths.append(path)
        print(f"wrote {path}  ({symbol})")

    print(f"\n# {len(paths)} configs. Worst case if every entry fires: "
          f"{args.max_total_positions} positions x {args.per_trade_pct:g}% "
          f"= {args.max_total_positions * args.per_trade_pct:g}% of equity at risk.")
    if args.universe_path:
        n_breadth = min(len(universe), args.max_universe) if args.max_universe > 0 \
            else len(universe)
        print(f"# breadth tally samples {n_breadth} of {len(universe)} symbols "
              "per bar (min_net is calibrated against THAT count — re-run "
              "oos_breadth if you change it).")
    # run_live steps executors sequentially inside one poll interval; past a few
    # hundred symbols the loop cannot finish within poll_seconds.
    if len(paths) > 300:
        print(f"# WARNING: {len(paths)} executors in one process will not finish "
              "a poll cycle in time (each step makes >=1 MT5 history call). "
              "Split the configs across several run_live.py processes, or use "
              "--limit to trade fewer symbols than you measure breadth over.")
    acct = f" --account {args.account}" if args.account else ""
    print(f"# launch:\n#   python scripts/run_live.py{acct} {out}/*.yaml")


if __name__ == "__main__":
    main()
